---
package_id: primefaces
package_version: '3.5'
distribution_raw_file: 3.5/primefaces-3.5-sources.jar
distribution_type: src
distribution_flavor: ''
platform_id: all
platform_vendor: all
platform_version: all
platform_arch: all
name: Primefaces 3.5 Source
description: Primefaces 3.5 Source
distribution_notes: ''
notify: 'yes'
distribution_version: 1
distribution_file_uuid_string: openlogic-primefaces-3.5-all-src-1
release_date: '2013-03-12'
distribution_file_uuid: !binary |-
  NzU5ZWNmYTQ4ODE4OWRiNmM4NjExY2IxNDQ1YTk4N2ZjYzExZjAxZTFmOTcw
  Zjg4MmJjNjg2YzFjNWRkYmY5Ng==
