package br.com.teste.models;
// Generated 10/11/2015 15:23:10 by Hibernate Tools 4.3.1



/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private int id;
     private String nome;
     private String endereco;
     private String numero;
     private String telefone;
     private String cidade;

    public Pessoa() {
    }

	
    public Pessoa(int id, String nome, String endereco) {
        this.id = id;
        this.nome = nome;
        this.endereco = endereco;
    }
    public Pessoa(int id, String nome, String endereco, String numero, String telefone, String cidade) {
       this.id = id;
       this.nome = nome;
       this.endereco = endereco;
       this.numero = numero;
       this.telefone = telefone;
       this.cidade = cidade;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
}


